api_platform:
    title: 'BileMo API'
    description: 'API PHONES'
    version: '0.0.1'
    show_webby: false
    collection:
        order: 'DESC'
        pagination:
            items_per_page: 10
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    formats:
        jsonld:                        ['application/ld+json']
        jsonhal:                       ['application/hal+json']
        xml:                           ['application/xml', 'text/xml']
        json:                          ['application/json']
        yaml:                          ['application/x-yaml']
        csv:                           ['text/csv']
        html:                          ['text/html']

    error_formats:
        jsonproblem:                   ['application/problem+json']
        jsonld:                        ['application/ld+json']


