api_platform:
    title: 'BileMo API'
    description: 'API PHONES'
    version: '0.0.1'
    show_webby: false
    collection :
        pagination :
            client_enabled : true 
            partial: true 
            enabled_parameter_name : pagination
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    http_cache:
        # invalidation:
        #     enabled: true
        #     varnish_urls: ['%env(VARNISH_URL)%']
        public: true
    defaults:
        cache_headers:
            max_age: 0
            shared_max_age: 3600
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonld:                        ['application/ld+json']
        jsonhal:                       ['application/hal+json']
        xml:                           ['application/xml', 'text/xml']
        json:                          ['application/json']
        yaml:                          ['application/x-yaml']
        csv:                           ['text/csv']
        html:                          ['text/html']

    error_formats:
        jsonproblem:                   ['application/problem+json']
        jsonld:                        ['application/ld+json']


