api_platform:

    title: 'BileMo API'
    description: 'API PHONES'
    version: '1.0.0'

    collection:
        order: 'DESC'
        pagination:
            items_per_page: 10

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    formats:
        jsonld:                        ['application/ld+json']

    error_formats:
        jsonproblem:                   ['application/problem+json']
        jsonld:                        ['application/ld+json']

    swagger:
        versions: [3]