nelmio_api_doc:
    documentation:
        host: 127.0.0.1:8000
        shemes: [http]
        info:
            title: Bilemo API
            description: An API who exposes our phones !
            version: 0.1
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
            security:
                - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api/docs # Accepts routes under /api except /api/doc
