security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        chain_provider:
            chain:
                providers: [reseller, customer]
        customer:
            entity: {class: App\Entity\Customer, property: email}
        reseller:
            entity: {class: App\Entity\Reseller, property: email}

    encoders:
            App\Entity\Reseller:
                    algorithm: bcrypt
            App\Entity\Customer:
                    algorithm: bcrypt

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            provider: chain_provider
            anonymous: true
            json_login:
                username_path:            email
                password_path:            password
                check_path:               /api/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        register:
            pattern:  ^/api/register
            stateless: true
            anonymous: true

        doc:
            pattern:  ^/api/doc
            stateless: true
            anonymous: true

        api:
            pattern:  ^/api
            stateless: true
            anonymous: false
            provider: chain_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }


    role_hierarchy:
        ROLE_RESELLER: ROLE_USER
