security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        reseller:
            entity:
                class: App\Entity\Reseller
                property: email
        admin:
            entity:
                class: App\Entity\Admin
                property: email
        all_users:
            chain:
                providers: ['admin','reseller']

    encoders:
        App\Entity\Reseller:
            algorithm: bcrypt
            cost: 15
        App\Entity\Customer:
            algorithm: bcrypt
            cost: 15
        App\Entity\Admin:
            algorithm: bcrypt
            cost: 15

    enable_authenticator_manager: true
    
    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/auth/login
            provider: all_users
            stateless: true
            login_throttling:
                max_attempts: 5
            json_login:
                username_path:            email
                password_path:            password
                check_path:               /api/auth/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            provider: all_users
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        api_doc:
            pattern: ^/api/docs?ui=re_doc


    access_control:
        - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_RESELLER: ROLE_USER
        ROLE_ADMIN: ROLE_RESELLER