security:
    providers:
        chain_provider:
            chain:
                providers: [reseller, customer]
        customer:
            entity: {class: App\Entity\Customer, property: email}
        reseller:
            entity: {class: App\Entity\Reseller, property: email}

    encoders:
        App\Entity\Reseller:
            algorithm: bcrypt
            cost: 15
        App\Entity\Customer:
            algorithm: bcrypt
            cost: 15

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            anonymous: true
            provider: chain_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern: ^/api/auth/login
            anonymous: true
            json_login:
                username_path:            email
                password_path:            password
                check_path:               /api/auth/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
            provider: chain_provider

        api_doc:
            pattern: ^/api/docs
            anonymous: true


    access_control:
        - { path: ^/api/docs, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/auth/(login|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
