security:
    providers:
        reseller:
            entity: {class: App\Entity\Reseller, property: email}

    encoders:
        App\Entity\Reseller:
            algorithm: bcrypt
            cost: 15

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        login:
#            pattern: ^/api/login
#            anonymous: true
#            json_login:
#                username_path:            email
#                password_path:            password
#                check_path:               /api/login
#                success_handler:          lexik_jwt_authentication.handler.authentication_success
#                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
#            guard:
#                authenticators:
#                    - lexik_jwt_authentication.jwt_token_authenticator
#            provider: chain_provider

#        api:
#            pattern: ^/api
#            stateless: true
#            anonymous: true
#
#        doc:
#            pattern: ^/api/docs
#            security: false
#            anonymous: true

    access_control:
        - { path: ^/api/(docs|login|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: IS_AUTHENTICATED_FULLY }
